import type { Metadata } from "next";
import "./globals.css";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import Nav from "../_components/Nav";
import Footer from "../_components/Footer";
import { Poppins } from "next/font/google";

export interface RootLayoutProps {
  children: React.ReactNode;
  params: { locale: string };
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export default async function RootLocaleLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body className={poppins.className}>
        <NextIntlClientProvider messages={messages}>
          <div
            className={`min-h-screen flex flex-col ${
              true ? "pt-[105px] sm:pt-[115px]" : ""
            } ${"className"}`}
          >
            <Nav theme="black" />
            <main className="flex-1">{children}</main>
            <Footer />
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
